---
title: "Typ grafu"
author: "Filip Děchtěrenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
  fig_caption: false
---

```{r set_language}
in_czech <- T
in_english <- !in_czech
if(in_czech) {
  lang <- "CZ"
} else {
  lang <- "EN"
}
```

```{r setup, code = readLines("D:/Documents/git/exams_vspj/common_chunks.R")}

```

```{r data generation, echo = FALSE, results = "hide"}
#possible_themes <- c("theme_bw","theme_dark","theme_minimal","theme_economist")

#curr_theme <- sample(possible_themes,1)
#theme_set(eval(parse(text=as.character(curr_theme))))

df_assignmnent <- get_var_desc(language = lang)
df_vardesc <- df_assignmnent$var_desc %>% unnest(cols = c(data))
text_question <- sample(df_assignmnent$question,1)

plot_types <- c("scatter","hist","pie","boxplot")
if(lang == "CZ") {
  plot_names <- c("Bodový graf","Histogram","Koláčový graf","Krabickový graf")  
} else {
  plot_names <- c("Scatter plot","Histogram","Pie chart","Box plot")  
}

curr_plot_type <- sample(plot_types,1)

if(curr_plot_type == "hist") {
  n <- sample(5:50,1)
  df_currvars <- sample_vars(df_vardesc, nvar = 1)
  
  ranges <- extract_ranges(df_currvars)
  
  curr_vals <- runif(n,ranges[1],ranges[2]) 
  curr_name <- df_currvars$name
  df_data <- tibble(!!curr_name:=curr_vals)
  p <- df_data %>% 
    ggplot(aes(x=!!sym(curr_name))) +
    geom_histogram(bins = 30) + 
    theme(aspect.ratio = 1)
} else if(curr_plot_type == "scatter") {
  n <- sample(5:50,1)
  df_currvars <- sample_vars(df_vardesc, nvar = 2)
  
  ranges <- extract_ranges(df_currvars)
  
  curr_vals1 <- runif(n,ranges[1,1],ranges[1,2]) 
  curr_name1 <- df_currvars$name[1]
  
  curr_vals2 <- runif(n,ranges[2,1],ranges[2,2]) 
  curr_name2 <- df_currvars$name[2]
  
  df_data <- tibble(!!curr_name1:=curr_vals1,!!curr_name2:=curr_vals2)
  
  p <- df_data %>% 
    ggplot(aes(x=!!sym(curr_name1), y=!!sym(curr_name2))) +
    geom_point() + 
    theme(aspect.ratio = 1)
} else if(curr_plot_type == "pie") {
  n <- sample(5:50,1)
  df_var_numeric <- sample_vars(df_vardesc, nvar = 1)
  df_var_factor <- sample_vars(df_vardesc, nvar = 1,var_type = "factor")
  
  ranges <- extract_ranges(df_var_numeric)
  values <- extract_values(df_var_factor)
  curr_vals1 <- runif(n,ranges[1],ranges[2]) 
  curr_name1 <- df_var_numeric$name[1]
  curr_vals2 <- sample(values,n,replace = T) 
  curr_name2 <- df_var_factor$name[1]
  
  df_data <- tibble(!!curr_name1:=curr_vals1,!!curr_name2:=curr_vals2)
  
  p <- df_data %>% 
    ggplot(aes(x="", y=!!sym(curr_name1), fill = !!sym(curr_name2))) +
    theme(aspect.ratio = 1) +
    geom_bar(width = 1, stat = "identity") +
    coord_polar("y", start=0) 
  
} else if(curr_plot_type == "boxplot") {
  n <- sample(10:50,1)
  
  df_var_numeric <- sample_vars(df_vardesc, nvar = 1)
  df_var_factor <- sample_vars(df_vardesc, nvar = 1,var_type = "factor")
  
  ranges <- extract_ranges(df_var_numeric)
  values <- extract_values(df_var_factor)
  curr_vals1 <- runif(n,ranges[1],ranges[2]) 
  curr_name1 <- df_var_numeric$name[1]
  curr_vals2 <- sample(values,n,replace = T) 
  curr_name2 <- df_var_factor$name[1]
  
  df_data <- tibble(!!curr_name1:=curr_vals1,!!curr_name2:=curr_vals2)
  
  p <- df_data %>% 
    ggplot(aes(x=!!sym(curr_name2), y=!!sym(curr_name1))) +
    theme(aspect.ratio = 1) +
    geom_boxplot()
  
  
}

questions <- plot_names
solutions <- rep(F,length(plot_names))
solutions[plot_types == curr_plot_type] <- T

o <- sample(1:length(plot_names))
questions <- questions[o]
solutions <- solutions[o]

if(lang == "CZ") {
  exam_title <- "Typ grafu"
} else {
  exam_title <- "Type of plot"
}

```

Question
========

```{r eval=in_czech, results='asis'}
cat("Určete typ následujícího grafu")
```

```{r eval=in_english, results='asis'}
cat("Determine the type of following plot")

```


```{r graf,echo = FALSE, warning =F,message=F}
p
```


```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

```{r eval=in_czech, results='asis'}
cat(sprintf("Tento graf se nazývá %s.", questions[solutions]))
```

```{r eval=in_english, results='asis'}
cat(sprintf("This plot is %s.", questions[solutions]))
```



Meta-information
================
extype: schoice
exsolution: `r mchoice2string(solutions, single = TRUE)`
exname: plot_type
extitle: `r exam_title`
expoints: 0.5
