---
title: "Deskriptivní statistika"
author: "Filip Děchtěrenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r}
if(runif(1) < 0.5) {
  plot_type <- "histogram"  
} else {
  plot_type <- "boxplot"  
}


in_czech <- F
in_english <- !in_czech
if(in_czech) {
  lang <- "CZ"
} else {
  lang <- "EN"
}

```

```{r setup, code = readLines("D:/Documents/git/exams_vspj/common_chunks.R")}

```

```{r data generation, echo = FALSE, results = "hide"}
df_assignmnent <- get_var_desc(language = lang)
df_vardesc <- df_assignmnent$var_desc %>% unnest(cols = c(data))
text_question <- sample(df_assignmnent$question,1)

df_currvars <- sample_vars(df_vardesc, nvar = 1)

var_ranges <- extract_ranges(df_currvars)
x_lower <- var_ranges[1,1]
x_upper <- var_ranges[1,2]
  
n  <- sample(1900:2600,1)
sd1 <- runif(1,1,3)
skew <- sample(c(-50, 0, 50),1)
x1 <- CensMFM::rMSN(n, 0, sd1, skew)
 
x1 <- standardize_value(x1) %>% 
  rescale_var_range(old_min = -4, old_max = 4, new_min = x_lower, new_max = x_upper) %>%
  round(df_currvars$round_val)

df_data <- tibble(!!df_currvars$name[1]:=x1)

## QUESTION/ANSWER GENERATION
questions <- character(3)
solutions <- logical(3)
explanations <- character(3)

# skewness

question <- c("Distribuce má zápornou šikmost.","Distribuce má přibližně nulovou šikmost.","Distribuce má kladnou šikmost.")

selected_question <- sample(1:3,1)

questions[1] <- question[selected_question]
solutions[1] <- if_else((skew<0&selected_question ==1) |(skew==0 & selected_question ==2)| (skew>0&selected_question ==3), T, F)
explanations[1] <- "Pokud distribuce dat 'padá' na jednu stranu, je zešikmená, jinak má nulovou šikmost. Pokud 'padá' vlevo, jde o kladnou šikmost, pokud vpravo, tak o zápornou."

# modus and mean vs median

question <- c("Modus je větší než median",
              "Modus je menší než median",
              "Modus je přibližně stejný jako median",
              "Modus je přibližně stejný jako průměr")
selected_question <- sample(1:length(question),1)
questions[2] <- question[selected_question]
solutions[2] <- if_else((skew>0&selected_question ==2) |(skew==0 & selected_question %in% c(3,4))| (skew<0&selected_question ==1), T, F)
explanations[2] <- if_else(skew == 0, "Distribuce je symetrická, a tedy median, průměr a modus jsou přibližně stejné",
                           if_else(skew >0, "Distribuce má kladnou šikmost, modus je tedy menší než průměr i median", "Distribuce má zápornou šikmost, modus je tedy větší než průměr i median"))

# mean vs median
question <- c( "Median je větší průměr",
              "Median je menší průměr",
              "Median je přibližně roven průměru")
              
selected_question <- sample(1:length(question),1)
questions[3] <- question[selected_question]
solutions[3] <- if_else((skew>0&selected_question ==1) |(skew==0 & selected_question == 3)| (skew<0&selected_question ==2), T, F)

explanations[3] <- if_else(skew == 0, "Distribuce je symetrická, a tedy median, průměr a modus jsou přibližně stejné",
                           if_else(skew >0, "Distribuce má kladnou šikmost, median je tedy menší než průměr", "Distribuce má zápornou šikmost, median je tedy větší než průměr"))

## permute order of solutions/questions
o <- sample(1:3)
questions <- questions[o]
solutions <- solutions[o]
explanations <- explanations[o]
```

Question
========

```{r, results='asis'}
cat(eval(parse(text=text_question)))
```

Získali jste graf rozložení proměnné `r df_currvars$name[1]`. 

```{r plot, fig.path = "", fig.cap = ""}
df_data %>% 
  ggplot(aes(x=!!sym(colnames(df_data)[1]))) +
  geom_density() + 
  theme(aspect.ratio = 1)
```

Zodpovězte následující otázky:


```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```


Solution
========

Zakreslíme-li do grafu průměr, median a modus, vypadá to následovně

```{r}
dy <- density(x1)$y %>% max()
dx <- density(x1)$x[density(x1)$y %>% which.max()]

labels <- tibble(x = c(mean(x1),median(x1), dx), y=rep(dy /2, 3), t= c("průměr","median","modus"))

df_data %>% 
  ggplot(aes(x=!!sym(colnames(df_data)[1]))) +
  geom_density() + 
  theme(aspect.ratio = 1) + 
  geom_segment(x = mean(x1), xend = mean(x1), y = 0, yend = dy*1.1) + 
  geom_segment(x = median(x1), xend = median(x1), y = 0, yend = dy*1.1) +
  geom_segment(x = dx, xend = dx, y = 0, yend = dy*1.1) +
  ggrepel::geom_text_repel(data = labels, aes(x,y, label = t))

  

```

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(
  ifelse(solutions, "Pravda", "Nepravda"),
  explanations, markup = "markdown")
```

Meta-information
================
extype: mchoice
exsolution: `r mchoice2string(solutions)`
exname: mean_median_modus
