---
title: "Deskriptivní statistika"
author: "Filip Děchtěrenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r}
if(runif(1) < 0.5) {
  plot_type <- "histogram"  
} else {
  plot_type <- "boxplot"  
}

in_czech <- T
in_english <- !in_czech
if(in_czech) {
  lang <- "CZ"
} else {
  lang <- "EN"
}

```

```{r setup, code = readLines("D:/Documents/git/exams_vspj/common_chunks.R")}

```

```{r data generation, echo = FALSE, results = "hide"}
df_assignmnent <- get_var_desc(language = lang)
df_vardesc <- df_assignmnent$var_desc %>% unnest(cols = c(data))
text_question <- sample(df_assignmnent$question,1)

df_currvars <- sample_vars(df_vardesc, nvar = 1)

var_ranges <- extract_ranges(df_currvars)
x_lower <- var_ranges[1,1]
x_upper <- var_ranges[1,2]

n  <- sample(50:100,1)
sd1 <- runif(1,0.5, 1.5)
sd2 <- runif(1,3, 6)

x1 <- rnorm(n, 0, sd1)
x2 <- rnorm(n, 0, sd2)

#x1 <- standardize_value(x1) %>% 
#  rescale_var_range(old_min = -4, old_max = 4, new_min = x_lower, new_max = x_upper) %>%
#  round(df_currvars$round_val)

#x2 <- standardize_value(x2) %>% 
#  rescale_var_range(old_min = -4, old_max = 4, new_min = x_lower, new_max = x_upper) %>%
#  round(df_currvars$round_val)


df_data1 <- tibble(`proměnná`:=x1)
df_data2 <- tibble(`proměnná`:=x2)

if(runif(1) < 0.5) {
  query_question <- "větší"
} else {
  query_question <- "menší"
}
if (lang == "CZ") {
  query_question_text <- query_question
} else {
  query_question_text <- recode(query_question, "větší" = "larger", "menší" = "smaller")
}


if(runif(1) < 0.5) {
  where_target <- "left"
  if(query_question == "větší") {
    df_left <- df_data2
    df_right <- df_data1
  } else {
    df_left <- df_data1
    df_right <- df_data2  
  }
  
} else {
  where_target <- "right"
  if(query_question == "větší") {
    df_right <- df_data2
    df_left <- df_data1
  } else {
    df_left <- df_data2
    df_right <- df_data1
  }
}

if(plot_type=="histogram") {
  if(lang == "CZ") {
    questions <- c("levý graf","pravý graf")  
  } else {
    questions <- c("left figure","right figure")  
  }
  
} else {
  
  if(lang == "CZ") {
    questions <- c("podmínka 1","podmínka 2")  
  } else {
    questions <- c("condition 1","condition 2")  
  }
}
if(where_target == "right") {
  solutions <- c(F,T)
} else {
  solutions <- c(T,F)
}

sdvar <- sample(c("var","sd"),1)

if(lang == "CZ") {
  sdvar_text <- recode(sdvar, "sd" = "směrodatnou odchylku", "var" = "rozptyl")
} else {
  sdvar_text <- recode(sdvar, "sd" = "standard deviation", "var" = "variance")
}



if(lang == "CZ") {
  exam_title <- "Vizualizace dat"
} else {
  exam_title <- "Visualization of the data"
}

```

Question
========

```{r eval=in_czech, results='asis'}
cat(sprintf("Následující %s náhodnou proměnnou. %s proměnná %s %s?", if_else(plot_type=="histogram", "dva grafy zobrazují", "graf zobrazuje"), if_else(plot_type=="histogram", "V kterém z grafů má", "V které podmínce má"),query_question_text, sdvar_text))
```

```{r eval=in_english, results='asis'}
cat(sprintf("Following %s shows measured variable. %s %s %s?", if_else(plot_type=="histogram", "two figures display", " figure displays"), if_else(plot_type=="histogram", "Which of the figures show ", "Which condition shows "),query_question_text, sdvar_text))

```


```{r plot, fig.path = "", fig.cap = "", warning=F}
if(lang == "CZ") {
  if (plot_type == "histogram") {
    p1 <- df_left %>% ggplot(aes(x = `proměnná`)) + geom_histogram(bins = 30)
    p2 <- df_right %>% ggplot(aes(x = `proměnná`)) + geom_histogram(bins = 30)  
    p1+p2
  } else if (plot_type == "boxplot"){
    df_data <- rbind(df_left %>% mutate(`podmínka` = "podmínka 1"), df_right %>% mutate(`podmínka` = "podmínka 2"))
    p <- df_data %>% ggplot(aes(x = `podmínka`, y = `proměnná`)) + geom_boxplot()
    p
  } else {
    df_data <- rbind(df_left %>% mutate(`podmínka` = "podmínka 1"), df_right %>% mutate(`podmínka` = "podmínka 2"))
    p <- df_data %>% ggplot(aes(x = `podmínka`, y = `proměnná`)) + geom_point(position = position_jitter(0.2))
    p
  }
  
} else {
  if (plot_type == "histogram") {
    p1 <- df_left %>% ggplot(aes(x = `proměnná`)) + geom_histogram(bins = 30) + xlab("variable")
    p2 <- df_right %>% ggplot(aes(x = `proměnná`)) + geom_histogram(bins = 30)  + xlab("variable")
    p1+p2
  } else if (plot_type == "boxplot"){
    df_data <- rbind(df_left %>% mutate(`condition` = "condition 1"), df_right %>% mutate(`condition` = "condition 2"))
    p <- df_data %>% ggplot(aes(x = `condition`, y = `proměnná`)) + geom_boxplot() + ylab("variable")
    p
  } else {
    df_data <- rbind(df_left %>% mutate(`conditon` = "condition 1"), df_right %>% mutate(`conditon` = "condition 2"))
    p <- df_data %>% ggplot(aes(x = `conditon`, y = `proměnná`)) + geom_point(position = position_jitter(0.2)) + ylab(variable)
    p
  }
  
}


```

```{r questionlist, echo = FALSE, results = "asis"}
exams::answerlist(questions, markup = "markdown")
```

Solution
========

```{r eval=in_czech, results='asis'}
cat(sprintf("
%s vlevo má v tomto případě %s roven %.3f a %s vpravo má %s %.3f. V tomto případě má tedy %s %s %s %s .", 
if_else(plot_type == "histogram", "Graf", "Podmínka"),
sdvar_text,
            if_else(sdvar == "var", round(var(df_left[["proměnná"]]),3), round(var(df_left[["proměnná"]]),3)),
if_else(plot_type == "histogram", "graf", "podmínka"),
            sdvar_text,
            if_else(sdvar == "var", round(var(df_right[["proměnná"]]),3), round(sd(df_right[["proměnná"]]),3)),
            query_question_text,
            sdvar_text,
            if_else(plot_type == "histogram", "graf", "podmínka"),
            if_else(where_target == "right", if_else(plot_type == "histogram", "vpravo", "2"), if_else(plot_type == "histogram", "vlevo", "1"))
            ))
```

```{r eval=in_english, results='asis'}
cat(sprintf("
Left %s has %s equal to %.3f and right %s has %s equal to %.3f. In this case, it shows  %s %s in the %s %s.", 
if_else(plot_type == "histogram", "graph", "condition"),
sdvar_text,
            if_else(sdvar == "var", round(var(df_left[["proměnná"]]),3), round(var(df_left[["proměnná"]]),3)),
  if_else(plot_type == "histogram", "graph", "condition"),
            sdvar_text,
            if_else(sdvar == "var", round(var(df_right[["proměnná"]]),3), round(sd(df_right[["proměnná"]]),3)),
            query_question_text,
            sdvar_text,
            if_else(where_target == "right", if_else(plot_type == "histogram", "right", "2"), if_else(plot_type == "histogram", "left", "1")),
if_else(plot_type == "histogram", "graph", "condition")
            ))

```


Meta-information
================
extype: schoice
exsolution: `r exams::mchoice2string(solutions, single = TRUE)`
exname: desc_plot
extitle: `r exam_title`
expoints: 0.5
