---
title: "Kontignenční tabulka"
author: "Filip Děchtěrenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r set_language}
in_czech <- T
in_english <- !in_czech
if(in_czech) {
  lang <- "CZ"
} else {
  lang <- "EN"
}
```

```{r setup, code = readLines("D:/Documents/git/exams_vspj/common_chunks.R")}

```

```{r data generation, echo = FALSE, results = "hide"}


df_assignmnent <- get_var_desc(language = lang)
df_vardesc <- df_assignmnent$var_desc %>% unnest(cols = c(data))
text_question <- sample(df_assignmnent$question,1)

n <- sample(100:500,1)
r <- runif(1,-1,1)

df_currvars <- df_vardesc %>% 
  filter(type == "factor") %>% 
  sample_n(2) %>% 
  rowwise() %>% 
  mutate(n_levels = get_n_factor_levels(values))

x_levels <- get_factor_levels(df_currvars$values[1])
y_levels <- get_factor_levels(df_currvars$values[2])

df <- generate_flat_ctable(n, r, x_levels, y_levels) %>% 
  mutate(x_categ = sprintf("%s-%s", df_currvars$name[1], x_categ),
         y_categ = sprintf("%s-%s", df_currvars$name[2], y_categ)) %>% 
  mutate(!!sym(df_currvars$name[1]):=x_categ, !!sym(df_currvars$name[2]):=y_categ)

xt <- xtabs(~y_categ+x_categ,df)

cont_coef <- sample(3,1)

if(cont_coef == 1) {
  f <-   pearson_cont_coef
  if(lang == "CZ") {
    asoc_coef <- "Pearsonův"
  } else {
    asoc_coef <- "Pearson's"
  }
} else if(cont_coef == 2){
  f <-   cramer_cont_coef
  if(lang == "CZ") {
    asoc_coef <- "Cramevův"
  } else {
    asoc_coef <- "Cramer's V"
  }
  
} else if(cont_coef == 3) {
  f <- cuporev_cont_coef
  if(lang == "CZ") {
    asoc_coef <- "Čuprovův"
  } else {
    asoc_coef <- "cuproev"
  }
  
} else {
  stop("incorrect contingency index")
}
  
solution <- f(chi_sq = (chisq.test(xt, correct = F))$statistic, n, ncol(df), nrow(df))

if(lang == "CZ") {
  exam_title <- "Kontingenční tabulka - asociace"
} else {
  exam_title <- "Contingency tables - asociation"
}
```

Question
========

```{r, results='asis'}
cat(eval(parse(text=text_question)))
```

```{r eval=in_czech, results='asis'}
cat(sprintf("Získali jsme data o proměnných '%s' a '%s' a zajímá nás, zda je mezi těmito proměnnými vztah.", df_currvars$name[1], df_currvars$name[2]))
```

```{r eval=in_english, results='asis'}
cat(sprintf("We collected data for variables '%s' and '%s' and we want to inspect, whether there is a relationship between variables.", df_currvars$name[1], df_currvars$name[2]))
```



```{r eval=in_czech, results='asis'}
cat("Data vypadají následovně:")
```

```{r eval=in_english, results='asis'}
cat("Data look as follows:")
```

```{r echo = FALSE}

table(df[[df_currvars$name[1]]], df[[df_currvars$name[2]]]) %>% knitr::kable()
#knitr::kable(xtabs(~))
#knitr::kable(ftable(df %>% select(-x_categ, -y_categ)), row.names = 1:2)
#epitab::contingency_table(list(df_currvars$name[1],df_currvars$name[2]), df)
#df %>% as.table()
#summarytools::ctable(x = df[[df_currvars$name[1]]], y = df[[df_currvars$name[2]]],
#      method = "render")
```

```{r eval=in_czech, results='asis'}
cat(sprintf("Určete %s koeficient kontingence (s přesností na 2 desetinná místa).", asoc_coef))
```

```{r eval=in_english, results='asis'}
cat(sprintf("Compute %s contingency coefficient (and round to 2 decimal places).", asoc_coef))
```

Solution
========
```{r eval=in_czech, results='asis'}
cat(sprintf("Pro danou kontingenční tabulku je výsledek %s", fmt(solution,2)))
```


```{r eval=in_english, results='asis'}
cat(sprintf("For given contingency table is the solution %s", fmt(solution,2)))
```

Meta-information
================
extype: num
exsolution: `r exams::fmt(solution,2)`
exname: cont_table_asoc
extol: 0.01
extitle: `r exam_title`
expoints: 1
