---
title: "Kontignenční tabulka - marginalizace"
author: "Filip Děchtěrenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r set_language}
in_czech <- T
in_english <- !in_czech
if(in_czech) {
  lang <- "CZ"
} else {
  lang <- "EN"
}
```

```{r setup, code = readLines("D:/Documents/git/exams_vspj/common_chunks.R")}

```

```{r data generation, echo = FALSE, results = "hide"}

df_assignmnent <- get_var_desc(language = lang)
df_vardesc <- df_assignmnent$var_desc %>% unnest(cols = c(data))
text_question <- sample(df_assignmnent$question,1)

n <- sample(100:500,1)
if(runif(1) < 0.5) {
  r <- runif(1,0.1,0.9)  
} else {
  r <- runif(1,-0.9,-0.1)  
}


df_currvars <- df_vardesc %>% 
  filter(type == "factor") %>% 
  sample_n(2) %>% 
  rowwise() %>% 
  mutate(n_levels = get_n_factor_levels(values))

x_levels <- get_factor_levels(df_currvars$values[1])
y_levels <- get_factor_levels(df_currvars$values[2])

df <- generate_flat_ctable(n, r, x_levels, y_levels) 
possible_x_lev <- unique(df$x_categ) %>% as.character()
possible_y_lev <- unique(df$y_categ) %>% as.character()

df <- df %>% 
  mutate(x_categ = sprintf("%s-%s", df_currvars$name[1], x_categ),
         y_categ = sprintf("%s-%s", df_currvars$name[2], y_categ)) %>% 
  mutate(x_categ = factor(x_categ,  levels = paste0(sprintf("%s-%s",df_currvars$name[1], x_levels))),
         y_categ = factor(y_categ,  levels = paste0(sprintf("%s-%s",df_currvars$name[2], y_levels)))) %>% 
  mutate(!!sym(df_currvars$name[1]):=x_categ, !!sym(df_currvars$name[2]):=y_categ)


if(runif(1) < 0.5) {
  selected_var <- "x"
  query_var <- df_currvars$name[1]
  group_var_levels <- intersect(y_levels, possible_y_lev)
  
  group_var <- df_currvars$name[2]
  
} else {
  selected_var <- "y"
  query_var <- df_currvars$name[2]
  group_var_levels <- intersect(x_levels, possible_x_lev)  

  group_var <- df_currvars$name[1]
}

selected_level <- sample(group_var_levels,1)

solution <- df %>% 
    group_by(!!sym(group_var)) %>% 
    summarize(n = n()) %>% 
  filter(!!sym(group_var) == sprintf("%s-%s",group_var, selected_level)) %>% 
  pull(n)


#
#colSm <- colSums(df %>% select(-!!df_currvars$name[2]))
#rowSm <- rowSums(df %>% select(-!!df_currvars$name[2]))
#df <- df %>% mutate_if(is.numeric, as.character)  

#df %>% mutate(`součet řádků` = rowSm) %>% 
#  rbind(tibble(!!df_currvars$name := "Součet řádků", ))
#  tibble::tbl_sum()

  if(runif(1) < 0.5) {
    xt <- xtabs(~x_categ + y_categ,df)    
    if (selected_var == "x") {
      if(lang == "CZ") {
          sum_type <- "sloupcové"
      } else {
          sum_type <- "column"
      }

      
    } else {
      if(lang == "CZ") {
          sum_type <- "řádkové"
      } else {
          sum_type <- "row"
      }
      
    }
  } else {
    xt <- xtabs(~y_categ + x_categ,df)
    
    if (selected_var == "x") {
      if(lang == "CZ") {
        sum_type <- "řádkové"
      } else {
        sum_type <- "row"
      }
      
    } else {
      if(lang == "CZ") {
          sum_type <- "sloupcové"
      } else {
          sum_type <- "column"
      }
    }
  }


if(lang == "CZ") {
  exam_title <- "Kontingenční tabulka - marginalizace"
} else {
  exam_title <- "Contingency tables - creation"
}

```

Question
========

```{r, results='asis'}
cat(eval(parse(text=text_question)))
```

```{r eval=in_czech, results='asis'}
cat(sprintf("Získali jsme data o proměnných '%s' a '%s'", df_currvars$name[1], df_currvars$name[2]))
```

```{r eval=in_english, results='asis'}
cat(sprintf("We collected data for variables '%s' and '%s'.", df_currvars$name[1], df_currvars$name[2]))
```

```{r eval=in_czech, results='asis'}
cat("Data vypadají následovně:")
```

```{r eval=in_english, results='asis'}
cat("Data look as follows:")
```

```{r echo = FALSE}
knitr::kable(xt)
```

```{r eval=in_czech, results='asis'}
cat(sprintf("Pokud bychom neměli brát ohled na rozdělení dle proměnné '%s', kolik je v datech pozorování, kde '%s'='%s'?", query_var, group_var, selected_level))
```

```{r eval=in_english, results='asis'}
cat(sprintf("If we omit the data division by variable '%s', how many observations do we have in cell, where '%s'='%s'?", query_var, group_var, selected_level))

```


Solution
========

```{r eval=in_czech, results='asis'}
cat(sprintf("Stačí sečíst %s součty v tabulce. Pro podkategorii '%s' je součet %s.", sum_type, selected_level, solution))
```

```{r eval=in_english, results='asis'}
cat(sprintf("We just need to compute %s sums in the table. For level '%s' is the sum  %s.", sum_type, selected_level, solution))

```


Meta-information
================
extype: num
exsolution: `r solution`
exname: cont_table_partial_sum
extitle: `r exam_title`
expoints: 1
