---
title: "Kontignenční tabulka"
author: "Filip Děchtěrenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r set_language}
in_czech <- T
in_english <- !in_czech
if(in_czech) {
  lang <- "CZ"
} else {
  lang <- "EN"
}
```

```{r setup, code = readLines("D:/Documents/git/exams_vspj/common_chunks.R")}

```

```{r data generation, echo = FALSE, results = "hide"}
#rm(list = ls())
#source("common_chunks.R")
df_assignmnent <- get_var_desc(language = lang)
df_vardesc <- df_assignmnent$var_desc %>% unnest(cols = c(data))
text_question <- sample(df_assignmnent$question,1)

n <- sample(100:500,1)

if(runif(1) < 0.5) {
  r <- runif(1,0.1,0.9)  
} else {
  r <- runif(1,-0.9,-0.1)  
}

df_currvars <- df_vardesc %>% 
  filter(type == "factor") %>% 
  sample_n(2) %>% 
  rowwise() %>% 
  mutate(n_levels = get_n_factor_levels(values))

x_levels <- get_factor_levels(df_currvars$values[1])
y_levels <- get_factor_levels(df_currvars$values[2])

df <- generate_flat_ctable(n, r, x_levels, y_levels) 
possible_x_lev <- unique(df$x_categ) %>% as.character()
possible_y_lev <- unique(df$y_categ) %>% as.character()

df <- df %>% 
  mutate(x_categ = sprintf("%s-%s", df_currvars$name[1], x_categ),
         y_categ = sprintf("%s-%s", df_currvars$name[2], y_categ)) %>% 
  mutate(x_categ = factor(x_categ,  levels = paste0(sprintf("%s-%s",df_currvars$name[1], x_levels))),
         y_categ = factor(y_categ,  levels = paste0(sprintf("%s-%s",df_currvars$name[2], y_levels)))) %>% 
  mutate(!!sym(df_currvars$name[1]):=x_categ, !!sym(df_currvars$name[2]):=y_categ)



cont_coef <- sample(3,1)

if(runif(1) < 0.5) {
  selected_var <- "x"
  query_var <- df_currvars$name[1]
  query_var_levels <- intersect(x_levels, possible_x_lev)
  group_var <- df_currvars$name[2]
  
  group_var_levels <- intersect(y_levels, possible_y_lev)  
  
} else {
  selected_var <- "y"
  query_var <- df_currvars$name[2]
  query_var_levels <- intersect(y_levels, possible_y_lev)  
  
  group_var <- df_currvars$name[1]
  group_var_levels <- intersect(x_levels, possible_x_lev)
}

selected_level_group <- sample(group_var_levels,1)
selected_level_query <- sample(query_var_levels,1)

  if(runif(1) < 0.5) {
    xt <- xtabs(~x_categ + y_categ,df) 
    
    if (selected_var == "x") {
      
      if(lang == "CZ") {
          sum_type <- "ke sloupcům"
      } else {
          sum_type <- "column"
      }
      
      xt_prop <- prop.table(xt,2)
    } else {
      if(lang == "CZ") {
          sum_type <- "k řádkům"
      } else {
          sum_type <- "row"
      }
      
      xt_prop <- prop.table(xt,1)
    }
  } else {
    xt <- xtabs(~y_categ + x_categ,df)
    
    if (selected_var == "x") {
      if(lang == "CZ") {
          sum_type <- "k řádkům"
      } else {
          sum_type <- "row"
      }
      xt_prop <- prop.table(xt,1)
    } else {
      if(lang == "CZ") {
          sum_type <- "ke sloupcům"
      } else {
          sum_type <- "column"
      }
      
      xt_prop <- prop.table(xt,2)

    }
  }


solution <- df %>% 
        group_by(!!sym(group_var), !!sym(query_var), .drop = F ) %>% 
        summarize(n = n()) %>% 
        group_by(!!sym(group_var), .drop = F ) %>%
        mutate(n_tot = sum(n),
               f = n/n_tot) %>% 
  ungroup() %>% 
  filter(!!sym(group_var) == sprintf("%s-%s",group_var,selected_level_group), 
         !!sym(query_var) == sprintf("%s-%s",query_var,selected_level_query)) %>% 
        pull(f)

if(lang == "CZ") {
  exam_title <- "Kontingenční tabulka - relativní frekvence"
} else {
  exam_title <- "Contingency tables - relative frequencies"
}

```

Question
========

```{r, results='asis'}
cat(eval(parse(text=text_question)))
```

```{r eval=in_czech, results='asis'}
cat(sprintf("Získali jsme data o proměnných '%s' a '%s'", df_currvars$name[1], df_currvars$name[2]))
```

```{r eval=in_english, results='asis'}
cat(sprintf("We collected data for variables '%s' and '%s'.", df_currvars$name[1], df_currvars$name[2]))
```

```{r eval=in_czech, results='asis'}
cat("Data vypadají následovně:")
```

```{r eval=in_english, results='asis'}
cat("Data look as follows:")
```

```{r echo = FALSE}
xt %>% knitr::kable()

#knitr::kable(xtabs(~))
#knitr::kable(ftable(df %>% select(-x_categ, -y_categ)), row.names = 1:2)
#epitab::contingency_table(list(df_currvars$name[1],df_currvars$name[2]), df)
#df %>% as.table()
#summarytools::ctable(x = df[[df_currvars$name[1]]], y = df[[df_currvars$name[2]]],
#      method = "render")
```

```{r eval=in_czech, results='asis'}
cat(sprintf("Vyjádříme-li tabulku v relativních četnostech vzhledem %s, kolik procent pozorování bude spadat do bunky '%s'='%s' a '%s'='%s'. Zaokrouhlujte na celá procenta.", sum_type, group_var, selected_level_group, query_var, selected_level_query))
```

```{r eval=in_english, results='asis'}
cat(sprintf("If we express the table in relative frequencies relative to %s sums, how many percent of data will fall into cell '%s'='%s' and '%s'='%s'. Round to whole percentages.", sum_type, group_var, selected_level_group, query_var, selected_level_query))

```


Solution
========

```{r eval=in_czech, results='asis'}
cat(sprintf("Tabulka relativních četností vzhledem %s vypadá následovně:", sum_type))
```

```{r eval=in_english, results='asis'}
cat(sprintf("Tabel with relative frequencies relative to %s looks as follows:", sum_type))

```


```{r }
xt_prop %>% knitr::kable(digits = 2)
```


```{r eval=in_english, results='asis'}
cat(sprintf("For given cell, the solution is %s%%.", exams::fmt(solution*100,0)))
```

```{r eval=in_czech, results='asis'}
cat(sprintf("Pro danou buňku je výsledek %s%%.", exams::fmt(solution*100,0)))

```

Meta-information
================
extype: num
exsolution: `r exams::fmt(solution*100,0)`
exname: cont_table_rel_freq
extol: 0.01
extitle: `r exam_title`
expoints: 1
