---
title: "Normal distribution - range"
author: "Filip Děchtěrenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r}
curr_theme <- NULL
```

```{r setup, code = readLines("D:/Documents/git/exams_vspj/common_chunks.R")}

```

```{r data generation, echo = FALSE, message=T}

df_assignmnent <- get_prob_var(distr_type = "normal", curr_theme = curr_theme, norm_type = "range")
df_vardesc <- df_assignmnent$var_desc %>% unnest(cols = c(data))
text_settings <- sample(df_assignmnent$settings,1)
text_question_range <- sample(df_assignmnent$question_range,1)

if(is.na(df_vardesc$mu_range)) {
  mu_lower <- 1
  mu_upper <- 10 
} else {
  mu_ranges <- str_split(df_vardesc$mu_range, "_", simplify = T)
  mu_lower <- as.numeric(mu_ranges[1])
  mu_upper <- as.numeric(mu_ranges[2])
}


if(is.na(df_vardesc$mu_param)) {
  mu_param <- sample(mu_lower:mu_upper,1)  
} else {
  mu_param <- df_vardesc$mu_param
}


if(is.na(df_vardesc$sigma_range)) {
  sigma_lower <- 1
  sigma_upper <- 10 
} else {
  sigma_ranges <- str_split(df_vardesc$sigma_range, "_", simplify = T)
  sigma_lower <- as.numeric(sigma_ranges[1])
  sigma_upper <- as.numeric(sigma_ranges[2])
}


if(is.na(df_vardesc$sigma_param)) {
  sigma_param <- sample(sigma_lower:sigma_upper,1)  
} else {
  sigma_param <- df_vardesc$sigma_param
}

should_continue <- T
while(should_continue) {
  k1 <- rnorm(1, mu_param, sigma_param) %>% round()
  k2 <- rnorm(1, mu_param, sigma_param) %>% round()
  if(k1 != k2) {
    should_continue <- F
  }
  k_lower <- min(k1, k2)
  k_upper <- max(k1, k2)
}



mu_text_tmp <- case_when(
  mu_param == 0 ~ df_vardesc$mu_0,
  mu_param == 1 ~ df_vardesc$mu_1,
  mu_param >= 2 & mu_param <= 4 ~ df_vardesc$mu_2_4,
  mu_param >= 5 & mu_param <= 9 ~ df_vardesc$mu_5_9,
  mu_param >= 10         ~ df_vardesc$mu_10more
)

mu_text <- sprintf("%d %s",mu_param, mu_text_tmp)

sigma_text_tmp <- case_when(
  sigma_param == 0 ~ df_vardesc$sigma_0,
  sigma_param == 1 ~ df_vardesc$sigma_1,
  sigma_param >= 2 & sigma_param <= 4 ~ df_vardesc$sigma_2_4,
  sigma_param >= 5 & sigma_param <= 9 ~ df_vardesc$sigma_5_9,
  sigma_param >= 10         ~ df_vardesc$sigma_10more
)

sigma_text <- sprintf("%d %s",sigma_param, sigma_text_tmp)


k_text_tmp <- case_when(
  k_upper == 0 ~ df_vardesc$k_0,
  k_upper == 1 ~ df_vardesc$k_1,
  k_upper >= 2 & k_upper <= 4 ~ df_vardesc$k_2_4,
  k_upper >= 5 & k_upper <= 9 ~ df_vardesc$k_5_9,
  k_upper >= 10         ~ df_vardesc$k_10more
)

if(is.na(k_text_tmp)) {
  k_text <- sprintf("%d-%d",  k_lower, k_upper)
} else {
  k_text <- sprintf("%d-%d %s", k_lower, k_upper, k_text_tmp)
}


#if (k == n/2& runif(1) < 0.5) {
#  k_text <- sprintf("%s polovinu ", quantifier, n, k_text_tmp)
#}



l <- probability_normal_setting_range(k_lower, k_upper, mu_param, sigma_param)
solution <- l$solution
explanation <- l$explanation
```

Question
========

```{r, results='asis'}
cat(eval(parse(text=text_settings)))
cat(eval(parse(text=text_question_range)))
```

Solution
========

```{r echo = FALSE, results='asis'}
cat(explanation)
```

Meta-information
================
extype: num
exsolution: `r exams::fmt(solution,3)`
exname: normal_prob_range
extol: 0.001
extitle: Výpočet pravděpodobnosti
expoints: 1
