---
title: "Normal distribution - mean"
author: "Filip Děchtěrenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r possible_parameters}
curr_theme <- NULL
```

```{r setup, code = readLines("D:/Documents/git/exams_vspj/common_chunks.R")}

```

```{r data generation, echo = FALSE, message=T}

df_assignmnent <- get_prob_var(distr_type = "normal", curr_theme = curr_theme)
df_vardesc <- df_assignmnent$var_desc %>% unnest(cols = c(data))
text_settings <- sample(df_assignmnent$settings,1)
text_question <- sample(df_assignmnent$question_mean,1)

if(is.na(df_vardesc$mu_range)) {
  mu_lower <- 1
  mu_upper <- 10 
} else {
  mu_ranges <- str_split(df_vardesc$mu_range, "_", simplify = T)
  mu_lower <- as.numeric(mu_ranges[1])
  mu_upper <- as.numeric(mu_ranges[2])
}


if(is.na(df_vardesc$mu_param)) {
  mu_param <- sample(mu_lower:mu_upper,1)  
} else {
  mu_param <- df_vardesc$mu_param
}


if(is.na(df_vardesc$sigma_range)) {
  sigma_lower <- 1
  sigma_upper <- 10 
} else {
  sigma_ranges <- str_split(df_vardesc$sigma_range, "_", simplify = T)
  sigma_lower <- as.numeric(sigma_ranges[1])
  sigma_upper <- as.numeric(sigma_ranges[2])
}


if(is.na(df_vardesc$sigma_param)) {
  sigma_param <- sample(sigma_lower:sigma_upper,1)  
} else {
  sigma_param <- df_vardesc$sigma_param
}


if(is.na(df_vardesc$n_range)) {
  n_lower <- 1
  n_upper <- 10 
} else {
  n_ranges <- str_split(df_vardesc$n_range, "_", simplify = T)
  n_lower <- as.numeric(n_ranges[1])
  n_upper <- as.numeric(n_ranges[2])
}


if(is.na(df_vardesc$n_param)) {
  n <- sample(n_lower:n_upper,1)  
} else {
  n <- df_vardesc$n_param
}

k <- rnorm(1, mu_param, sigma_param/n) %>% round()



quantifier <- sample(c("alespoň", "nejvýše", "méně než", "více než"),1)  



mu_text_tmp <- case_when(
  mu_param == 0 ~ df_vardesc$mu_0,
  mu_param == 1 ~ df_vardesc$mu_1,
  mu_param >= 2 & mu_param <= 4 ~ df_vardesc$mu_2_4,
  mu_param >= 5 & mu_param <= 9 ~ df_vardesc$mu_5_9,
  mu_param >= 10         ~ df_vardesc$mu_10more
)

mu_text <- sprintf("%d %s",mu_param, mu_text_tmp)

sigma_text_tmp <- case_when(
  sigma_param == 0 ~ df_vardesc$sigma_0,
  sigma_param == 1 ~ df_vardesc$sigma_1,
  sigma_param >= 2 & sigma_param <= 4 ~ df_vardesc$sigma_2_4,
  sigma_param >= 5 & sigma_param <= 9 ~ df_vardesc$sigma_5_9,
  sigma_param >= 10         ~ df_vardesc$sigma_10more
)

if (df_vardesc$sigma_type == "var") {
  sigma_text <- sprintf("%d %s",sigma_param^2, sigma_text_tmp)
} else {
  sigma_text <- sprintf("%d %s",sigma_param, sigma_text_tmp)
}

k_text_tmp <- case_when(
  k == 0 ~ df_vardesc$k_0,
  k == 1 ~ df_vardesc$k_1,
  k >= 2 & k <= 4 ~ df_vardesc$k_2_4,
  k >= 5 & k <= 9 ~ df_vardesc$k_5_9,
  k >= 10         ~ df_vardesc$k_10more
)
if(is.na(k_text_tmp)) {
  k_text <- sprintf("%s %d", quantifier, k)
} else {
  k_text <- sprintf("%s %d %s", quantifier, k, k_text_tmp)
}

n_text_tmp <- case_when(
  n == 0 ~ df_vardesc$n_0,
  n == 1 ~ df_vardesc$n_1,
  n >= 2 & n <= 4 ~ df_vardesc$n_2_4,
  n >= 5 & n <= 9 ~ df_vardesc$n_5_9,
  n >= 10         ~ df_vardesc$n_10more
)
if(is.na(n_text_tmp)) {
  n_text <- sprintf("%d", n)
} else {
  n_text <- sprintf("%d %s", n, n_text_tmp)
}



l <- probability_normal_setting_mean(k, n, mu_param, sigma_param, quantifier)
solution <- l$solution
explanation <- l$explanation
```

Question
========

```{r, results='asis'}
cat(eval(parse(text=text_settings)))
cat(eval(parse(text=text_question)))
```

Solution
========

```{r echo = FALSE, results='asis'}
cat(explanation)
```

Meta-information
================
extype: num
exsolution: `r exams::fmt(solution,3)`
exname: normal_prob_mean
extol: 0.001