---
title: "Poisson distribution"
author: "Filip Děchtěrenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r setup, code = readLines("D:/Documents/git/exams_vspj/common_chunks.R")}

```

```{r data generation, echo = FALSE, message=T}

df_assignmnent <- get_prob_var(distr_type = "poisson")
df_vardesc <- df_assignmnent$var_desc %>% unnest(cols = c(data))
text_question <- sample(df_assignmnent$question,1)

if(is.na(df_vardesc$lambda_range)) {
  lambda_lower <- 1
  lambda_upper <- 10 
} else {
  lambda_ranges <- str_split(df_vardesc$lambda_range, "_", simplify = T)
  lambda_lower <- as.numeric(lambda_ranges[1])
  lambda_upper <- as.numeric(lambda_ranges[2])
}


if(is.na(df_vardesc$lambda_param)) {
  lambda_param <- sample(lambda_lower:lambda_upper,1)  
} else {
  lambda_param <- df_vardesc$lambda_param
}


k <- sample(0:lambda_param, 1)

if(k == lambda_param) {
  quantifier <- sample(c("nejvýše", "méně než", "právě"),1)
  
} else if(k == 0){
  quantifier <- sample(c("více než", "právě"), 1)
  
} else {
  quantifier <- sample(c("alespoň", "nejvýše", "méně než", "více než", "právě"),1)  
}


lambda_text_tmp <- case_when(
  lambda_param == 1 ~ df_vardesc$lambda_1,
  lambda_param >= 2 & lambda_param <= 4 ~ df_vardesc$lambda_2_4,
  lambda_param >= 5 & lambda_param <= 9 ~ df_vardesc$lambda_5_9,
  lambda_param >= 10         ~ df_vardesc$lambda_10more
)

lambda_text <- sprintf("%d %s",lambda_param, lambda_text_tmp)

k_text_tmp <- case_when(
  k == 0 ~ df_vardesc$k_0,
  k == 1 ~ df_vardesc$k_1,
  k >= 2 & k <= 4 ~ df_vardesc$k_2_4,
  k >= 5 & k <= 9 ~ df_vardesc$k_5_9,
  k >= 10         ~ df_vardesc$k_10more
)
if(is.na(k_text_tmp)) {
  k_text <- sprintf("%s %d", quantifier, k)
} else {
  k_text <- sprintf("%s %d %s", quantifier, k, k_text_tmp)
}


#if (k == n/2& runif(1) < 0.5) {
#  k_text <- sprintf("%s polovinu ", quantifier, n, k_text_tmp)
#}

# TODO - vyresit sude lambda

l <- probability_poisson_setting(lambda_param,k,quantifier)
solution <- l$solution
explanation <- l$explanation
```

Question
========

```{r, results='asis'}
cat(eval(parse(text=df_vardesc$text_settings)))
```

```{r, results='asis'}
cat(eval(parse(text=text_question)))
```

Solution
========

```{r echo = FALSE, results='asis'}
cat(explanation)
```

Meta-information
================
extype: num
exsolution: `r exams::fmt(solution,3)`
exname: poisson_prob
extol: 0.001