---
title: "Chi square independence"
author: "Filip Děchtěrenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r set_language}
in_czech <- T
in_english <- !in_czech
if(in_czech) {
  lang <- "CZ"
} else {
  lang <- "EN"
}
```

```{r setup, code = readLines("D:/Documents/git/exams_vspj/common_chunks.R")}

```

```{r data generation, echo = FALSE, results = "hide"}
library(exams)

df_assignmnent <- get_var_desc(language = lang)
df_vardesc <- df_assignmnent$var_desc %>% unnest(cols = c(data))
text_question <- sample(df_assignmnent$question,1)

n <- sample(100:500,1)
r <- runif(1,-1,1)

df_currvars <- df_vardesc %>% 
  filter(type == "factor") %>% 
  sample_n(2) %>% 
  rowwise() %>% 
  mutate(n_levels = get_n_factor_levels(values))

x_levels <- get_factor_levels(df_currvars$values[1])
y_levels <- get_factor_levels(df_currvars$values[2])

df <- generate_flat_ctable(n, r, x_levels, y_levels) %>% 
  mutate(x_categ = sprintf("%s-%s", df_currvars$name[1], x_categ),
         y_categ = sprintf("%s-%s", df_currvars$name[2], y_categ)) %>% 
  mutate(!!sym(df_currvars$name[1]):=x_categ, !!sym(df_currvars$name[2]):=y_categ)

xt <- xtabs(~y_categ+x_categ,df)

chisq <- chisq.test(xt, correct = F)

if (lang == "CZ") {
  questions <- c("Proměnné jsou nezávislé", "Proměnné jsou závislé")
} else {
  questions <- c("Variables are independent", "Variables are dependent")
}

#question_type <- sample(2,1)

#if(runif(1) < 0.5) {
#  query_type <- "p_val"
#  query_text <- "p hodnotu"
#  solution <- chisq$p.value
#  questions[[2]] <- c("Jaká je p-hodnota testu?")
  
if(chisq$p.value < 0.05) {
    solutions <- c(F,T)
    if (lang == "CZ") {
      solution_text <- "Protože p hodnota je menší než 0.05, zamítáme nulovou hypotézu o nezávislosti proměnných. Proměnné jsou tedy na sobě závislé."
    } else {
      solution_text <- "Because p value is lower than 0.05, we reject null hypothesis about independence of variables. Thus variables are dependent."
    }
    
  } else {
    solutions <- c(T,F)
    
    if (lang == "CZ") {
      solution_text <- "Protože p hodnota je větší než 0.05, nemůžeme zamítnout nulovou hypotézu o nezávislosti proměnných."
    } else {
      solution_text <- "Because p value is greater than 0.05, we can't reject nullnull hypothesis about independence of variables."
    }
  }
  
#} else {
#  query_type <- "chi_sq"
#  query_text <- "testovou statistiku $\\chi^2$"
#  solution <- chisq$statistic
#  questions[[2]] <- c("Jaká je hodnota testové statistiky $\\chi^2$?")
#  if(chisq$p.value < 0.05) {
#    solution_text <- "Protože je p hodnota menší než 0.05, zamítáme nulovou hypotézu o nezávislosti proměnných. Proměnné jsou tedy na sobě závislé."
#    solutions[[2]] <- c(F,T)
#  } else {
#    solution_text <- "Protože je p hodnota větší než 0.05, nemůžeme zamítnout nulovou hypotézu o nezávislosti proměnných."
#    solutions[[2]] <- c(T,F)
#  }
  
#}
if(lang == "CZ") {
  exam_title <- "Testování hypotéz"
} else {
  exam_title <- "Hypothesis testing"
}


```

Question
========

```{r, results='asis'}
cat(eval(parse(text=text_question)))
```

```{r eval=in_czech, results='asis'}
cat(sprintf("Získali jsme data o proměnných '%s' a '%s' a zajímá nás, zda je mezi těmito proměnnými vztah.", df_currvars$name[1], df_currvars$name[2]))
```

```{r eval=in_english, results='asis'}
cat(sprintf("We collected data for variables '%s' and '%s' and we want to inspect, whether there is a relationship between variables.", df_currvars$name[1], df_currvars$name[2]))
```

```{r eval=in_czech, results='asis'}
cat("Data vypadají následovně:")
```

```{r eval=in_english, results='asis'}
cat("Data look as follows:")
```


```{r echo = FALSE}

table(df[[df_currvars$name[1]]], df[[df_currvars$name[2]]]) %>% knitr::kable()
#knitr::kable(xtabs(~))
#knitr::kable(ftable(df %>% select(-x_categ, -y_categ)), row.names = 1:2)
#epitab::contingency_table(list(df_currvars$name[1],df_currvars$name[2]), df)
#df %>% as.table()
#summarytools::ctable(x = df[[df_currvars$name[1]]], y = df[[df_currvars$name[2]]],
#      method = "render")
```

```{r eval=in_czech, results='asis'}

cat("Rozhodněte, zda jsou proměnné na sobě nezávislé či závislé. Pro test použijte hladinu významnosti $\\alpha$=5%.") 
```

```{r eval=in_english, results='asis'}
cat("Decide whether are the variables independent or not. Use significance level $\\alpha$=5%. ")
```



```{r questionlist, echo = FALSE, results = "asis"}
answerlist(unlist(questions), markup = "markdown")
```

Solution
========
```{r eval=in_czech, results='asis'}
cat(sprintf("Pro danou kontingenční tabulku je p-hodnota testu nezávislosti rovna %s.", exams::fmt(chisq$p.value,3)))
```

```{r eval=in_english, results='asis'}
cat(sprintf("For given contingency table is the p-value equal to %s.", exams::fmt(chisq$p.value,3)))
```

`r solution_text` 

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(solutions, single = TRUE)`
exname: chi_square_independence
extol: 0.001
extitle: `r exam_title`
expoints: 0.5
