---
title: "Hypothesis testing"
author: "Filip Děchtěrenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r set_language}
in_czech <- T
in_english <- !in_czech
if(in_czech) {
  lang <- "CZ"
} else {
  lang <- "EN"
}
```

```{r setup, code = readLines("D:/Documents/git/exams_vspj/common_chunks.R")}

```


```{r data generation, echo = FALSE}

df_assignmnent <- get_var_desc(language = lang)
df_vardesc <- df_assignmnent$var_desc %>% unnest(cols = c(data))
text_question <- sample(df_assignmnent$question,1)

n <- sample(c(7,14,21,28,35,42),1)
r <- runif(1,-1,1)

df_currvars <- sample_vars(df_vardesc, nvar = 2)

# generate X,Y data
df_data <- safe_generate_correlated_data(n,r,df_currvars)
mm <- df_data[[df_currvars$name[1]]] 
mm <- mm %>% matrix(nrow = n/6) %>% round()

sigma <- runif(1,df_currvars$sd[1]*0.8, df_currvars$sd[1]*1.2)
is_signif <- sample(0:1,1)

alpha <- sample(c(0.001, 0.01, 0.05),1)
alpha_param <- round(alpha*100,1)
if(is_signif) {
  p_val <- runif(1,0, alpha)
} else {
  p_val <- runif(1,alpha+alpha/10, 1)
}



possible_test_types <- c("one-sample","two-sample","paired")

test_type <- sample(possible_test_types, 1)

if(test_type == "one-sample") {
  if(lang == "CZ") {
    test_type_text <- "od teoretické hodnoty"
  } else {
    test_type_text <- "from ome theoretical value"
  }
  
} else if (test_type == "two-sample") {
  
  if(lang == "CZ") {
    test_type_text <- "mezi dvěma skupinami"
  } else {
    test_type_text <- "between two groups"
  }
} else {
  
  if(lang == "CZ") {
    test_type_text <- "mezi dvěma opakovanými měřeními téže skupiny."
  } else {
    test_type_text <- "between two repeated measures of the same group."
  }
}

if(runif(1) < 0.5) {
  
  if(lang == "CZ") {
    population_true_text <- "platila nulová hypotéza"
  } else {
    population_true_text <- "null hypothesis is true"
  }
  population_true <- "H0"
} else {
  if(lang == "CZ") {
    population_true_text <- "platila alternativní hypotéza"
  } else {
    population_true_text <- "alternative hypothesis is true"
  }
  population_true <- "HA"
}


if(lang == "CZ") {
  questions <- c("Chyba I. druhu", "Chyba II. druhu", "správný závěr")
} else {
  questions <- c("Type I error", "Type II error", "correct decision")
}
solutions <- rep(F,3)
if(is_signif& population_true == "H0") {
  if(lang == "CZ") {
    explanation_text <- "Jelikož v populaci platí nulová hypotéza, ale my jsme nulovou zamítli, učinili jsme chybu I. druhu."
  } else {
    explanation_text <- "Because null is true in population, but we rejected it, we made Type I error."
  }
  solutions[1] <- T
} else if(!is_signif& population_true == "HA") {
  if(lang == "CZ") {
    explanation_text <- "Jelikož v populaci platí alternativní hypotéza, ale my jsme nulovou nezamítli, učinili jsme chybu II. druhu."
  } else {
    explanation_text <- "Because alternative is true in population, but we did not reject null, we made Type II error."
  }
  
  solutions[2] <- T
} else {
  if(is_signif) {
    if(lang == "CZ") {
      explanation_text <- "Učinili jsme správný závěr, jelikož v populaci platí alternativní hypotéza a my jsme nulovou zamítli ve prospěch alternativní."
    } else {
     explanation_text <- "We made a correct decision, because in population, alternative hypothesis is true and we rejected null in favour of alternative."
    }
      
  } else {
    if(lang == "CZ") {
      explanation_text <- "Učinili jsme správný závěr, jelikož v populaci platí nulová hypotéza a my jsme nulovou nezamítli."
    } else {
     explanation_text <- "We made a correct decision, because in population, null hypothesis is true and we did not rejected null."
    }
    
  }
  
  solutions[3] <- T
}
  
o <- sample(1:length(questions))
questions <- questions[o]
solutions <- solutions[o]



if(lang == "CZ") {
  exam_title <- "Testování hypotéz - chyba I. a II. druhu"
} else {
  exam_title <- "Hypothesis testing - Type I and II errors"
}

```



Question
========
```{r, results='asis'}
cat(eval(parse(text=text_question)))
```

```{r eval=in_czech, results='asis'}
cat(sprintf("Byli jsme požádáni o zpracování analýzy, zda se hodnoty proměnné '%s' na nasbíraném vzorku liší %s. Pracujeme s hladinou významnosti %s%%. Získali jsme p-hodnotu rovnou %.3f. Pokud by ve skutečnosti %s a my správně interpretovali výsledky testy, které z následujících tvrzení platí?", df_currvars$name[1], test_type_text, alpha_param, p_val %>% round(3), population_true_text))
```

```{r eval=in_english, results='asis'}
cat(sprintf("We were asked to perform analysis, whether values of variable '%s' from the sample differ %s. We work with significance level %s%%. We got p-value equal to %.3f. If in reality %s and we correctly interpreted results of our test, which of the following statements holds?", df_currvars$name[1], test_type_text, alpha_param, p_val %>% round(3), population_true_text))
```




```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

`r explanation_text`

Meta-information
================
extype: mchoice
exsolution: `r mchoice2string(solutions, single = T)`
exname: error_type
extitle: `r exam_title`
expoints: 0.5

