---
title: "Hypothesis testing"
author: "Filip Děchtěrenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r set_language}
in_czech <- T
in_english <- !in_czech
if(in_czech) {
  lang <- "CZ"
} else {
  lang <- "EN"
}
```

```{r setup, code = readLines("D:/Documents/git/exams_vspj/common_chunks.R")}

```


```{r data generation, echo = FALSE}

df_assignmnent <- get_var_desc(language = lang)
df_vardesc <- df_assignmnent$var_desc %>% unnest(cols = c(data))
text_question <- sample(df_assignmnent$question,1)

n <- sample(c(7,14,21,28,35,42),1)
r <- runif(1,-1,1)

df_currvars <- sample_vars(df_vardesc, nvar = 2)

# generate X,Y data
df_data <- safe_generate_correlated_data(n,r,df_currvars)
mm <- df_data[[df_currvars$name[1]]] 
mm <- mm %>% matrix(nrow = n/6) %>% round()

sigma <- runif(1,df_currvars$sd[1]*0.8, df_currvars$sd[1]*1.2)
is_signif <- sample(0:1,1)

alpha <- sample(c(0.001, 0.01, 0.05),1)
alpha_param <- round(alpha*100,1)
if(is_signif) {
  p_val <- runif(1,0, alpha)
} else {
  p_val <- runif(1,alpha+alpha/10, 1)
}



possible_test_types <- c("one-sample","two-sample","paired")

test_type <- sample(possible_test_types, 1)

if(test_type == "one-sample") {
  if(lang == "CZ") {
    test_type_text <- "od teoretické hodnoty"
  } else {
    test_type_text <- "from ome theoretical value"
  }
  
} else if (test_type == "two-sample") {
  
  if(lang == "CZ") {
    test_type_text <- "mezi dvěma skupinami"
  } else {
    test_type_text <- "between two groups"
  }
} else {
  
  if(lang == "CZ") {
    test_type_text <- "mezi dvěma opakovanými měřeními téže skupiny."
  } else {
    test_type_text <- "between two repeated measures of the same group."
  }
}




questions <- character()
solutions <- logical()

if(runif(1) < 0.5) {# correct 
  if(is_signif) {
    if(lang == "CZ") {
      questions[1] <- "Zamítáme nulovou hypotézu"
    } else {
      questions[1] <- "Reject null hypothesis"
    }
    
    solutions[1] <- T
  } else {
    if(lang == "CZ") {
      questions[1] <- "Nemítáme nulovou hypotézu"
    } else {
      questions[1] <- "Don't reject null hypothesis"
    }
    
    solutions[1] <- F
  }
} else { # incorrect
  if(is_signif) {
    if(lang == "CZ") {
      questions[1] <- sample(c("Nezamítáme nulovou hypotézu", "Platí nulová hypotéza", "Neplatí alternativní hypotéza"),1)
    } else {
      questions[1] <- 
        questions[1] <- sample(c("Don't reject null hypothesis", "Null hypothesis is true", "Alternative hypothesis is not true"),1)
    }
    
    
    solutions[1] <- F
  } else {
    if(lang == "CZ") {
      questions[1] <- "Zamítáme nulovou hypotézu"
    } else {
      questions[1] <- "We reject null hypothesis"
    }
    
    
    solutions[1] <- F
  }
}


test_query <- sample(possible_test_types,2)
if(lang == "CZ") {
  
  questions[2] <- case_when(
    test_query[1] == "one-sample" ~ "Použijeme jednovýběrový test",
    test_query[1] == "two-sample" ~ sample(c("Použijeme dvouvýběrový test", "Použijeme nepárový dvouvýběrový test", "Použijeme nepárový test s dvěma skupinami"),1),
    test_query[1] == "paired" ~ sample(c("Použijeme párový test", "Použijeme párový dvouvýběrový test", "Použijeme párový test s dvěma skupinami"),1)
  )
  questions[3] <- case_when(
    test_query[2] == "one-sample" ~ "Použijeme jednovýběrový test",
    test_query[2] == "two-sample" ~ sample(c("Použijeme dvouvýběrový test", "Použijeme nepárový dvouvýběrový test", "Použijeme nepárový test s dvěma skupinami"),1),
    test_query[2] == "paired" ~ sample(c("Použijeme párový test", "Použijeme párový dvouvýběrový test", "Použijeme párový test s dvěma skupinami"),1)
  )} else {
    questions[2] <- case_when(
      test_query[1] == "one-sample" ~ "We use one-sample test",
      test_query[1] == "two-sample" ~ sample(c("We use two-sample test", "We use non-paired two-sample test", "We use non-paired test with two groups"),1),
      test_query[1] == "paired" ~ sample(c("We use paired test", "We use paired two-sample test", "We use paired test with two groups"),1)
    )
    
    questions[3] <- case_when(
      test_query[2] == "one-sample" ~ "We use one-sample test",
      test_query[2] == "two-sample" ~ sample(c("We use two-sample test", "We use non-paired two-sample test", "We use non-paired test with two groups"),1),
      test_query[2] == "paired" ~ sample(c("We use paired test", "We use paired two-sample test", "We use paired test with two groups"),1)
    )
  }

solutions[2] <- test_query[1] == test_type
solutions[3] <- test_query[2] == test_type

o <- sample(1:length(questions))
questions <- questions[o]
solutions <- solutions[o]

if(lang == "CZ") {
  
  
  explanation_text_tmp1 <- case_when(
    test_type == "one-sample" ~ "Protože nás zajímá rozdíl vzorku od teoretické hodnoty, použijeme jednovýběrový test. ",
    test_type == "two-sample" ~ "V případě rozdílu mezi dvěma vzorky, které jsou nezávislé, použijeme dvouvýběrový test. ",
    test_type == "paired" ~ "V případě rozdílu mezi dvěma vzorky, které jsou závislé (třeba měření před a po intervenci), použijeme párový test. "
  )
  
  explanation_text_tmp2 <- if_else(is_signif  == 1, "Jelikož je p-hodnota menší než hladina významnosti, můžeme zamítnout nulovou hypotézu ve prospěch alternativní.", "Jelikož je p-hodnota větší než hladina významnosti, nemůžeme zamítnout nulovou hypotézu ve prospěch alternativní. Pozor, neznamená to, že platí nulová hypotéza, pouze ji nemůžeme vyvrátit."
  )
} else {
  explanation_text_tmp1 <- case_when(
    test_type == "one-sample" ~ "Because we are interested in difference from theoretical value, we use one-sample test. ",
    test_type == "two-sample" ~ "In case of difference between two samples, which are independent, we use two sample test. ",
    test_type == "paired" ~ "In case of difference between two samples, which are dependent (such as measuring same group before and after measurement), we use paired test. "
  )
  
  explanation_text_tmp2 <- if_else(is_signif  == 1, "Because p-value is lower than significance level, we can reject null in favour of alternative.", "Because p-value is larger than significance level, we can't rejct null in favour of alternative.")
}
explanation_text <- sprintf("%s%s", explanation_text_tmp1, explanation_text_tmp2)

if(lang == "CZ") {
  exam_title <- "Testování hypotéz"
} else {
  exam_title <- "Hypothesis testing"
}
```



Question
========
```{r, results='asis'}
cat(eval(parse(text=text_question)))
```

```{r eval=in_czech, results='asis'}
cat(sprintf("Byli jsme požádáni o zpracování analýzy, zda se hodnoty proměnné '%s' na nasbíraném vzorku liší %s. Pracujeme s hladinou významnosti %s%%. Získali jsme p-hodnotu rovnou %.3f. Které z následujících tvrzení platí?", df_currvars$name[1], test_type_text, alpha_param, p_val %>% round(3)))
```

```{r eval=in_english, results='asis'}
cat(sprintf("We were asked to perform analysis, whether values of variable '%s' from the sample differ %s. We work with significance level %s%%. We got p-value equal to %.3f. Which of the following statements holds?", df_currvars$name[1], test_type_text, alpha_param, p_val %>% round(3)))
```

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

`r explanation_text`

Meta-information
================
extype: mchoice
exsolution: `r mchoice2string(solutions)`
exname: hypothesis_testing
extitle: `r exam_title`
expoints: 1.5
