---
title: "one sample T-test"
author: "Filip Děchtěrenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r set_language}
in_czech <- T
in_english <- !in_czech
if(in_czech) {
  lang <- "CZ"
} else {
  lang <- "EN"
}
```

```{r setup, code = readLines("D:/Documents/git/exams_vspj/common_chunks.R")}

```


```{r data generation, echo = FALSE}

df_assignmnent <- get_var_desc(language = lang)
df_vardesc <- df_assignmnent$var_desc %>% unnest(cols = c(data))
text_question <- sample(df_assignmnent$question,1)

n <- sample(c(7,14,21,28,35,42),1)
r <- runif(1,-1,1)

df_currvars <- sample_vars(df_vardesc, nvar = 2)

# generate X,Y data
df_data <- safe_generate_correlated_data(n,r,df_currvars)
mm <- df_data[[df_currvars$name[1]]] 
mm <- mm %>% matrix(nrow = n/6) 

x_bar <- mean(mm)
sx  <- sd(mm)


popul_mean <- rnorm(1, x_bar, df_currvars$sd[1]/4) %>% round(df_currvars$round_val[1])

t <- sqrt(n)*(x_bar - popul_mean)/sx
p_val <- 2*pt(abs(t), n-1,lower.tail = F)

if(lang == "CZ") {
  exam_title <- "Testování hypotéz"
} else {
  exam_title <- "Hypothesis testing"
}
```



Question
========
```{r, results='asis'}
cat(eval(parse(text=text_question)))
```

```{r eval=in_czech, results='asis'}
cat(sprintf("Byli jsme požádáni o zpracování analýzy, zda se hodnoty proměnné '%s' liší (oboustranně) od teoretické hodnoty, %s. Jaká je p-hodnota příslušného testu? Data vypadají následovně: `", df_currvars$name[1],exams::fmt(popul_mean, zeros = F)))
```


```{r eval=in_english, results='asis'}
cat(sprintf("We were asked to perform analysis, whether variable '%s' differ (two-sided) from theoretical value %s. What is the p-value of corresponding test? Data look as follows: `", df_currvars$name[1],exams::fmt(popul_mean, zeros = F)))
```



```{r graf,echo = FALSE, warning =F,message=F}
mm %>% knitr::kable()
```



Solution
========

```{r eval=in_czech, results='asis'}
cat(sprintf("Protože neznáme směrodatnou odchylku populace, musíme použít t-test. Nejprve data zkopírujeme do Jamovi. V Jamovi poté vybereme T-Tests-> One sample-tests, vybereme proměnnou a z výsledků zkopírujeme p-hodnotu. V tomto případě je výsledek %s", p_val %>% exams::fmt(digits = 3)))
```

```{r eval=in_english, results='asis'}
cat(sprintf("Because we don't know population SD, we need to use t-test. First, we copy the data into Jamovi, then we select T-tests -> One sample t-tests, select the variable and copy the p-value. In this case, the p-value is %s", p_val %>% exams::fmt(digits = 3)))
```


Meta-information
================
extype: num
exsolution: `r fmt(p_val,3)`
exname: one sample t-test
extol: 0.001
extitle: `r exam_title`
expoints: 1
