---
title: "Hypothesis testing"
author: "Filip Děchtěrenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r set_language}
in_czech <- T
in_english <- !in_czech
if(in_czech) {
  lang <- "CZ"
} else {
  lang <- "EN"
}
```

```{r setup, code = readLines("D:/Documents/git/exams_vspj/common_chunks.R")}

```


```{r data generation, echo = FALSE}

test_type <- sample(1:5,1)

operator <- case_when(
  test_type == 1 ~ "less",
  test_type == 2 ~ "more",
  test_type == 3 ~ "neq",
  test_type == 4 ~ "leq",
  test_type == 5 ~ "geq"
)

operator_text <- case_when(
  test_type == 1 ~ "<",
  test_type == 2 ~ ">",
  test_type == 3 ~ "\\neq",
  test_type == 4 ~ "\\leq",
  test_type == 5 ~ "\\geq"
)

HA <- sprintf("$$ H_A: \\mu %s \\mu_0$$", operator_text) 

mu_0 <- sample(10:70,1)

if(lang == "CZ") {
questions <- c(sample(c(sprintf("Testujeme, že průměr populace, ze které pochází vzorek, se liší od teoretické hodnoty %d",mu_0),
                        "Testujeme, že průměr populace, ze které pochází vzorek, se liší od teoretické hodnoty $\\mu_0$"),1),
               sample(c(sprintf("Testujeme, že průměr populace, ze které pochází vzorek, je větší než teoretická hodnota %d",mu_0),
                        "Testujeme, že průměr populace, ze které pochází vzorek, je větší než teoretická hodnota $\\mu_0$"),1),
               sample(c(sprintf("Testujeme, že průměr populace, ze které pochází vzorek, je menší než teoretická hodnota %d",mu_0),
                        "Testujeme, že průměr populace, ze které pochází vzorek, je menší než teoretická hodnota $\\mu_0$"),1),
               "Použijeme jednostranný test",
               "Použijeme oboustranný test",
               "Altenativní hypotéza není správně definována")
} else {
  questions <- c(sample(c(sprintf("We test that the mean of the population, from which the sample is selected, is different from theoretical value %d",mu_0),
                        "We test that the mean of the population, from which the sample is selected, is different from theoretical value $\\mu_0$"),1),
               sample(c(sprintf("We test that the mean of the population, from which the sample is selected, is larger than the theoretical value %d",mu_0),
                        "We test that the mean of the population, from which the sample is selected, is larger than the theoretical value $\\mu_0$"),1),
               sample(c(sprintf("We test that the mean of the population, from which the sample is selected, is smaller than the theoretical value %d",mu_0),
                        "We test that the mean of the population, from which the sample is selected, is smaller than the theoretical value $\\mu_0$"),1),
               "We use one-sided test",
               "We use two-sided test",
               "Alternative hypothesis is not well defined")
}

solutions <- case_when(
  operator == "less" ~ c(F,F,T,T,F,F),
  operator == "more" ~ c(F,T,F,T,F,F),
  operator == "neq" ~ c(T,F,F,F,T,F),
  operator == "leq" ~ c(F,F,F,F,F,T),
  operator == "geq" ~ c(F,F,F,F,F,T)
)

if(lang == "CZ") {
explanation <- case_when(
  operator == "less" ~ "Alternativní hypotéza zachycuje stav, kdy je skutečný průměr populace nižší než daná hodnota. Použijme tedy jednostranný test.",
  operator == "more" ~ "Alternativní hypotéza zachycuje stav, kdy je skutečný průměr populace vyšší než daná hodnota. Použijme tedy jednostranný test.",
  operator == "neq" ~ "Alternativní hypotéza zachycuje stav, kdy je skutečný průměr populace jiný než daná hodnota (nižší nebo vyšší). Použijme tedy oboustranný test.",
  operator == "leq" ~ "Alternativní hypotéza je zadaná nesprávně (v nulové i alternativní je znak =).",
  operator == "geq" ~ "Alternativní hypotéza je zadaná nesprávně (v nulové i alternativní je znak =)."
) 
} else {
  explanation <- case_when(
  operator == "less" ~ "Alternative hypothesis corresponds to the state, in which population mean is lower than given value. We will use one-tailed test.",
  operator == "more" ~ "Alternative hypothesis corresponds to the state, in which population mean is higher than given value. We will use one-tailed test.",
  operator == "neq" ~ "Alternative hypothesis corresponds to the state, in which population mean is different than given value (lower or higher). We will use two-sided test.",
  operator == "leq" ~ "Alternative hypothesis is stated incorrectly (both null and alternative contain equal sign).",
  operator == "geq" ~ "Alternative hypothesis is stated incorrectly (both null and alternative contain equal sign)."
)
}
  
o <- sample(1:length(questions), 3)
questions <- questions[o]
solutions <- solutions[o]

if(lang == "CZ") {
questions[4] <- "Žádná z možností není správná"
solutions[4] <- !any(solutions)
} else {
  questions[4] <- "None of the above"
  solutions[4] <- !any(solutions)
 
 }

if(lang == "CZ") {
  exam_title <- "Testování hypotéz - Testování hypotéz - jedno/oboustranný test"
} else {
  exam_title <- "Hypothesis testing - one/two-tailed tests"
}


```



Question
========

```{r eval=in_czech, results='asis'}
cat("Při čtení metodické části bakalářské práce jste narazili na následující část:")
```

```{r eval=in_english, results='asis'}
cat("While reading method section of your friends's thesis, you ran into following lines:")
```


$$ H_0: \mu = \mu_0$$
`r HA`

```{r eval=in_czech, results='asis'}
cat(sprintf("Dále tam je tvrzení, že '$\\mu_0=$ %d'. Která z následujících odpovědí je pravdivá:", mu_0))
```

```{r eval=in_english, results='asis'}
cat(sprintf("Also, there is a statement that '$\\mu_0=$ %d'. Which of the following is true:", mu_0))
```


```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

`r explanation`

Meta-information
================
extype: mchoice
exsolution: `r mchoice2string(solutions)`
exname: tailedness
extitle: `r exam_title`
expoints: 1.5

