---
title: "Typ grafu"
author: "Filip Děchtěrenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
  fig_caption: false
---

```{r set_language}
in_czech <- T
in_english <- !in_czech
if(in_czech) {
  lang <- "CZ"
} else {
  lang <- "EN"
}
```

```{r setup, code = readLines("D:/Documents/git/exams_vspj/common_chunks.R")}

```

```{r data generation, echo = FALSE, results = "hide"}

df_assignmnent <- get_var_desc(language = lang)
df_vardesc <- df_assignmnent$var_desc %>% unnest(cols = c(data))
text_question <- sample(df_assignmnent$question,1)

n <- sample(5:10,1)
r <- runif(1,-1,1)

df_currvars <- sample_vars(df_vardesc, nvar = 2)

df_data <- safe_generate_correlated_data(n,r,df_currvars)

X <- df_data[[1]]
Y <- df_data[[2]]
lm1 <- lm(Y~X, df_data)

if(lang == "CZ") {
  exam_title <- "Regrese - odhad parametru"
} else {
  exam_title <- "Regression - parameter estimation"
}

```



Question
========
```{r, results='asis'}
cat(eval(parse(text=text_question)))
```

```{r eval=in_czech, results='asis'}
cat(sprintf("Lineární závislost popisujeme rovnicí ve tvaru $y = b_1x+b_0$. Spočítejte regresní koeficient $b_1$ přímky předpovídající proměnnou '%s' v závislosti na proměnné '%s'. Data vypadají následovně:", df_currvars$name[2], df_currvars$name[1]))
```

```{r eval=in_english, results='asis'}
cat(sprintf("Linear relationship is captured by equation $y = b_1x+b_0$. Compute regression coefficient $b_1$ for the line predicting variable '%s' from variable '%s'. Data looks as follows:", df_currvars$name[2], df_currvars$name[1]))
```


```{r graf,echo = FALSE, warning =F,message=F}
df_data %>% knitr::kable()
```

Solution
========
```{r eval=in_czech, results='asis'}
cat("Když si vizualizujeme data, vypadají následovně:")
```

```{r eval=in_english, results='asis'}
cat("When we visualize data, it looks like follows:")
```


```{r plot, fig.path = "", fig.cap = ""}
df_data %>% 
  ggplot(aes(x=!!sym(colnames(df_data)[1]), y=!!sym(colnames(df_data)[2]))) +
  geom_point() + 
  theme(aspect.ratio = 1)
```

```{r eval=in_czech, results='asis'}
cat("Regresní koeficienty můžeme spočítat pomocí Regression nástroje v Jamovi")
```

```{r eval=in_english, results='asis'}
cat("We can compute regression using Regression tool in Jamovi")
```


```{r eval=in_czech, results='asis'}
cat("Regresní koeficienty jsou: ")
```

```{r eval=in_english, results='asis'}
cat("Regression coefficients are: ")
```

* $b_0$ = `r exams::fmt(coef(lm1)[1])`
* $b_1$ = `r exams::fmt(coef(lm1)[2])`

```{r eval=in_czech, results='asis'}
cat("Pokud zobrazíme regresní přímku do grafu, vychází to následovně.")
```

```{r eval=in_english, results='asis'}
cat("If we add regression line into figure, it looks as follows.")
```

```{r plot-plus-regression, fig.path = "", fig.cap = ""}
df_data %>% 
  ggplot(aes(x=!!sym(colnames(df_data)[1]), y=!!sym(colnames(df_data)[2]))) +
  geom_point() + 
  theme(aspect.ratio = 1) +
  stat_smooth(method ="lm", se = F, formula='y ~ x')

```



Meta-information
================
extype: num
exsolution: `r exams::fmt(coef(lm1)[2])`
extol: 0.01
exname: regression_slope
extitle: `r exam_title`
expoints: 1
