---
title: "Range estimation"
author: "Filip Děchtěrenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r set_language}
in_czech <- T
in_english <- !in_czech
if(in_czech) {
  lang <- "CZ"
} else {
  lang <- "EN"
}
```

```{r setup, code = readLines("D:/Documents/git/exams_vspj/common_chunks.R")}

```


```{r data generation, echo = FALSE}

df_assignmnent <- get_var_desc(language = lang)
df_vardesc <- df_assignmnent$var_desc %>% unnest(cols = c(data))
text_question <- sample(df_assignmnent$question,1)

n <- sample(c(36,42,48),1)
r <- runif(1,-1,1)

df_currvars <- sample_vars(df_vardesc, nvar = 2)

# generate X,Y data
df_data <- safe_generate_correlated_data(n,r,df_currvars)
mm <- df_data[[df_currvars$name[1]]] 
mm <- mm %>% matrix(nrow = n/6) %>% round(df_currvars$round_val[1])

interval_range <- sample(c(95,90,99),1)

u <- qt(1-(1-interval_range/100)/2, n-1) %>% round(2)
s <- sd(mm) %>% round(2)
m <- mean(mm) %>% round(2)
LB <- m-u*s/sqrt(n) %>% round(1)
UB <- m+u*s/sqrt(n) %>% round(1)

if(runif(1) < 0.5) {
  x <- LB
  if(lang == "CZ") {
    interval_type <- "dolní"
  } else {
    interval_type <- "lower"
  }
} else {
  x <- UB
  
  if(lang == "CZ") {
    interval_type <- "horní"
  } else {
    interval_type <- "upper"
  }
}

if(lang == "CZ") {
  lower_limit <- "Dolní limit je"
  upper_limit <- "Horní limit je"
} else {
  lower_limit <- "Lower boundary is"
  upper_limit <- "Upper boundary is"
  
}

if(lang == "CZ") {
  exam_title <- "Intervalový odhad"
} else {
  exam_title <- "Confidence intervals"
}

```



Question
========
```{r, results='asis'}
cat(eval(parse(text=text_question)))
```


```{r eval=in_czech, results='asis'}
cat(sprintf("Když se zaměříme pouze na proměnnou %s, vypadají data pro tento výběr data následovně:",  df_currvars$name[1]))
```

```{r eval=in_english, results='asis'}
cat(sprintf("When we focus only on variable %s, the data looks as follows:",  df_currvars$name[1]))
```

```{r graf,echo = FALSE, warning =F,message=F}
mm %>% knitr::kable()
```


```{r eval=in_czech, results='asis'}
cat(sprintf("Spočítejte interval, ve kterém se nachází s pravděpodobností %d%% průměr celé populace (konfidenční interval). Pro výsledek zadejte pouze %s hranici intervalu a zaokrouhlete na 1 desetinné místo.",  interval_range,interval_type))
```

```{r eval=in_english, results='asis'}
cat(sprintf("Compute confidence interval, in which the population mean lies with probability %d%% . Report just %s bound of the interval and round to 1 decimal point.",  interval_range,interval_type))

```

Solution
========


```{r eval=in_czech, results='asis'}
cat(sprintf("Pro výpočet %d%% intervalu spolehlivosti zkopírujeme data do Jamovi a konfidenční interval spočítáme pomocí nástroje T-Tests-> One sample T-test",  interval_range))
```

```{r eval=in_english, results='asis'}
cat(sprintf("To compute %d%% confidence interval for the mean, we copy the data into Jamovi and select T-Tests-> One sample T-test:",  interval_range))

```

```{r eval=in_czech, results='asis'}
cat(sprintf("Interval tedy je ve tvaru %s",  sprintf("[%.1f,%.1f]", LB, UB)))
```

```{r eval=in_english, results='asis'}
cat(sprintf("Confidence interval is in form %s", sprintf("[%.1f,%.1f]", LB, UB)))

```

Answerlist
----------
* `r lower_limit` $`r LB %>% exams::fmt(digits = 1)`$.
* `r upper_limit` $`r UB %>% exams::fmt(digits = 1)`$.

Meta-information
================
extype: num
exsolution: `r exams::fmt(x,digits = 1)`
exname: confidence_interval
extol: 0.1
extitle: `r exam_title`
expoints: 1
