---
title: "Point estimation"
author: "Filip Děchtěrenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r set_language}
in_czech <- T
in_english <- !in_czech
if(in_czech) {
  lang <- "CZ"
} else {
  lang <- "EN"
}
```

```{r setup, code = readLines("D:/Documents/git/exams_vspj/common_chunks.R")}

```


```{r data generation, echo = FALSE}

df_assignmnent <- get_var_desc(language = lang)
df_vardesc <- df_assignmnent$var_desc %>% unnest(cols = c(data))
text_question <- sample(df_assignmnent$question,1)

n <- sample(c(36,42,48),1)
r <- runif(1,-1,1)

df_currvars <- sample_vars(df_vardesc, nvar = 2)

# generate X,Y data
df_data <- safe_generate_correlated_data(n,r,df_currvars)
mm <- df_data[[df_currvars$name[1]]] 
mm <- mm %>% matrix(nrow = n/6) %>% round()

interval_range <- sample(c(95,90,99),1)

u <- qnorm(1-(1-interval_range/100)/2) %>% round(2)
s <- sd(mm) %>% round(2)
m <- mean(mm) %>% round(2)
LB <- m-u*s/sqrt(n) %>% round(1)
UB <- m+u*s/sqrt(n) %>% round(1)
delta <- (0.5*runif(1, (UB-LB)/4, 0.8*(UB-LB))) %>% round(2)
n_estim <- ceiling(((u^2)*(s^2))/(delta^2))

if(lang == "CZ") {
  exam_title <- "Intervalový odhad"
} else {
  exam_title <- "Confidence intervals"
}
```



Question
========
```{r, results='asis'}
cat(eval(parse(text=text_question)))
```

```{r eval=in_czech, results='asis'}
cat(sprintf("Když se zaměříme pouze na proměnnou %s, vypadají data pro tento výběr data následovně:",  df_currvars$name[1]))
```

```{r eval=in_english, results='asis'}
cat(sprintf("When we focus only on variable %s, the data looks as follows:",  df_currvars$name[1]))
```

```{r graf,echo = FALSE, warning =F,message=F}
mm %>% knitr::kable()
```

```{r eval=in_czech, results='asis'}
cat(sprintf("Na základě těchto dat můžeme spočítat, že %d%% interval spolehlivosti je %s. Pokud bychom měli data se stejnou směrodatnou odchylkou jako v tomto vzorku, jaká by musela být velikost nového vzorku, aby přípustná chyba výběrového souboru při %d%% hladině významnosti nepřesáhla %.2f? Přípustnou chybou rozumíme vzdálenost měření od skutečného průměru.
",  interval_range,sprintf("[%.1f,%.1f]", LB, UB),100-interval_range, delta))
```

```{r eval=in_english, results='asis'}
cat(sprintf("Based on these data, we can compute that %d%% confidence interval is %s. If we had data with the same standard deviation as in this sample, what would be the size of the new sample so that the allowable sample error at the %d%% level of significance does not exceed  %.2f? By allowable sample error we mean distance of measurement to the true mean.
",  interval_range,sprintf("[%.1f,%.1f]", LB, UB),100-interval_range, delta))
```


Solution
========

```{r eval=in_czech, results='asis'}
cat(sprintf("Pro výpočet %d%% intervalu spolehlivosti pro průměr využijeme původní vzorce:",  interval_range))
```

```{r eval=in_english, results='asis'}
cat(sprintf("We use following formula for computation of %d%% confidence interval for the mean:",  interval_range))

```

$$ 
\begin{aligned}
\left[\bar{y} \, - \, u_{1-\frac{\alpha}{2}}\sqrt{\frac{s^2}{n}}, \; 
  \bar{y} \, + \, u_{1-\frac{\alpha}{2}}\sqrt{\frac{s^2}{n}}\right] 
\end{aligned}
$$


```{r eval=in_czech, results='asis'}
cat("a spočítat rozdíl krajních limit intervalu. Pokud si označíme přípustnou chybu jako $\\Delta$, platí následující vztah:")
```

```{r eval=in_english, results='asis'}
cat("and compute difference of interval bounds. If we set the allowed error as $\\Delta$, following relationship holds:")

```

 
$$ 
\begin{aligned}
 n \geq \frac{u_{1-\frac{\alpha}{2}}^2 \cdot s^2} {\Delta^2}
\end{aligned}
$$

```{r eval=in_czech, results='asis'}
cat(sprintf("V tomto případě je $u_{1-\\frac{\\alpha}{2}}$=%.2f, s = %.2f a $\\Delta$=%.2f. Výběr by tedy měl obsahovat alespoň %d pozorování.",  u, s,delta,n_estim))
```

```{r eval=in_english, results='asis'}
cat(sprintf("In this case, $u_{1-\\frac{\\alpha}{2}}$=%.2f, s = %.2f and $\\Delta$=%.2f. Sample should contain at least %d observations.",  u, s,delta,n_estim))

```


Meta-information
================
extype: num
exsolution: `r exams::fmt(n_estim,digits = 1)`
exname: confidence_interval_size
extol: 0
extitle: `r exam_title`
expoints: 1
