---
title: "Correlation - positive/negative"
author: "Filip Děchtěrenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r set_language}
in_czech <- T
in_english <- !in_czech
if(in_czech) {
  lang <- "CZ"
} else {
  lang <- "EN"
}
```

```{r setup, code = readLines("D:/Documents/git/exams_vspj/common_chunks.R")}

```

```{r data generation, echo = FALSE, results = "hide"}
## DATA GENERATION
df_assignmnent <- get_var_desc(language = lang)
df_vardesc <- df_assignmnent$var_desc %>% unnest(cols = c(data))
text_question <- sample(df_assignmnent$question,1)

n <- sample(80:120,1)
r1 <- runif(1,0.7,0.9)*sample(c(-1,1),1)
r2 <- runif(1,0.4,0.6)*sample(c(-1,1),1)

df_currvars <- sample_vars(df_vardesc, nvar = 2)

df_data1 <- safe_generate_correlated_data(n,r1,df_currvars)
df_data2 <- safe_generate_correlated_data(n,r2,df_currvars)

plot_titles <- c(df_assignmnent$group1,df_assignmnent$group2)
plot_left_title <- sample(plot_titles,1)
plot_right_title <- setdiff(plot_titles,plot_left_title)

if (runif(1) <0.5) {
  df_left <- df_data1  
  df_right <- df_data2
  plot_order <- "normal"
} else {
  df_left <- df_data2  
  df_right <- df_data1
  plot_order <- "flipped"
}


x_ranges <- df_currvars$values[1] %>% extract_ranges_vec()
xmin <- x_ranges[1]
xmax <- x_ranges[2]

y_ranges <- df_currvars$values[2] %>% extract_ranges_vec()
ymin <- y_ranges[1]
ymax <- y_ranges[2]
if (lang == "CZ") {
  questions <- c("Obě pozitivní","Obě negativní","Vlevo pozitivní, vpravo negativní","Vlevo negativní, vpravo pozitivní")  
} else {
  questions <- c("Both positive","Both negative","Left positive, right negative","Left negative, right positive")  
}

solutions <- rep(F,length(questions))
if (plot_order == "normal") {
  if(r1>0&r2>0) {
  solutions[1] <- T
} else if(r1<0&r2<0) {
  solutions[2] <- T
} else if(r1>0&r2<0) {
  solutions[3] <- T
}  else if(r1<0&r2>0) {
  solutions[4] <- T
}  
} else {
  if(r1>0&r2>0) {
  solutions[1] <- T
} else if(r1<0&r2<0) {
  solutions[2] <- T
} else if(r1>0&r2<0) {
  solutions[4] <- T
}  else if(r1<0&r2>0) {
  solutions[3] <- T
} 
}


o <- sample(1:length(questions))
questions <- questions[o]
solutions <- solutions[o]

if(lang == "CZ") {
  exam_title <- "Korelace - kladná/záporná"
} else {
  exam_title <- "Correlation - positive/negative"
}
```

Question
========

```{r, results='asis'}
cat(eval(parse(text=text_question)))
```


```{r eval=in_czech, results='asis'}
cat(sprintf("V následujících grafech vidíme vztahy mezi proměnnými '%s' a '%s' zvlášť pro podskupinu %s a %s. Rozhodněte, které korelace jsou kladné a které záporné.", df_currvars$name[1], df_currvars$name[2], df_assignmnent$group1, df_assignmnent$group2))
```

```{r eval=in_english, results='asis'}
cat(sprintf("In following plots, we can see relationship between variables '%s' a '%s' separately for groups %s and %s. Decide, whether each correlation is positive or negative.", df_currvars$name[1], df_currvars$name[2], df_assignmnent$group1, df_assignmnent$group2))
```

```{r eval=in_czech, results='asis'}
cat("Data vypadají následovně:")
```

```{r eval=in_english, results='asis'}
cat("Data look as follows:")
```

```{r graf,echo = FALSE, warning =F,message=F, fig.width=10}
p1 <- df_left %>% ggplot(aes(x = !!sym(df_currvars$name[1]),!!sym(df_currvars$name[2]))) + theme(aspect.ratio = 1) + 
  geom_point() + 
  ggtitle(plot_left_title)+ xlim(xmin,xmax) + ylim(ymin,ymax)

p2 <- df_right %>% ggplot(aes(x = !!sym(df_currvars$name[1]),!!sym(df_currvars$name[2]))) + theme(aspect.ratio = 1) + 
  geom_point() + 
  ggtitle(plot_right_title) + xlim(xmin,xmax) + ylim(ymin,ymax)
p1+p2
```

```{r eval=in_czech, results='asis'}
cat("Které korelace jsou kladné a které záporné?")
```

```{r eval=in_english, results='asis'}
cat("Which of the following correlations are positive/negative?")
```


```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========
```{r eval=in_czech, results='asis'}
cat(sprintf("Korelace pro levý graf je %s, pro pravý je %s. správná odpověď je tedy %s.", fmt(cor(df_left[[1]],df_left[[2]]),2), fmt(cor(df_right[[1]],df_right[[2]]),2), questions[solutions]))
```

```{r eval=in_english, results='asis'}
cat(sprintf("Correlation for left plot is %s, for right plot is %s. Correct answer is %s.", fmt(cor(df_left[[1]],df_left[[2]]),2), fmt(cor(df_right[[1]],df_right[[2]]),2), questions[solutions]))
```


Meta-information
================
extype: schoice
exsolution: `r mchoice2string(solutions, single = TRUE)`
exname: correlation_positive_negative
extitle: `r exam_title`
expoints: 0.5
