---
title: "Korelace"
author: "Filip Děchtěrenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r setup, code = readLines("D:/Documents/git/exams_vspj/common_chunks.R")}

```


```{r data generation, echo = FALSE, message=T}

df_assignmnent <- get_var_desc(curr_theme = "couples_theater")
df_vardesc <- df_assignmnent$var_desc %>% unnest(cols = c(data))
text_question <- sample(df_assignmnent$question,1)

n <- sample(5:10,1)
r <- runif(1,-1,1)

df_currvars <- sample_vars(df_vardesc, nvar = 2)

var_ranges <- extract_ranges(df_currvars)
x_lower <- var_ranges[1,1]
x_upper <- var_ranges[1,2]
y_lower <- var_ranges[2,1]
y_upper <- var_ranges[2,2]

should_continue <- T
n_try <- 0
while (should_continue) {
  n_try <- n_try+1
  if(n_try > 99) {
    stop("Impossible to generate, check the variables")
  }
  df <- generate_correlated_data(n,r)
  
  X <- df[, 1]  # standard normal (mu=0, sd=1)
  Y <- df[, 2]  # standard normal (mu=0, sd=1)
  
  X <- rescale_var(X,df_currvars$mean[1],df_currvars$sd[1]) %>% round(df_currvars$round_val[1])
  Y <- rescale_var(Y,df_currvars$mean[2],df_currvars$sd[2]) %>% round(df_currvars$round_val[2])
  
  should_continue <- !any(check_var(X, x_lower,x_upper) & check_var(Y, y_lower,y_upper))
}
df_data <- tibble(!!df_currvars$name[1]:=X,!!df_currvars$name[2]:=Y) 



```

Question
========
```{r, results='asis'}
cat(eval(parse(text=text_question)))
```

Data vypadají následovně:

```{r echo = FALSE}
knitr::kable(df_data)
```

Určete Pearsonův korelační koeficient (s přesností na 2 desetinná místa)

Solution
========
Korelaci spočítáme pomocí funkce CORREL, výsledek je `r exams::fmt(cor(X,Y),2)`.  
Bodový graf vypadá následovně:

```{r echo = FALSE}
df_data %>% 
  ggplot(aes(x=!!sym(colnames(df_data)[1]), y=!!sym(colnames(df_data)[2]))) +
  geom_point() + 
  theme(aspect.ratio = 1)
```

Meta-information
================
extype: num
exsolution: `r exams::fmt(cor(X,Y),2)`
exname: correlation
extol: 0.01