---
title: "Hypothesis testing"
author: "Filip Děchtěrenko"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r set_language}
in_czech <- T
in_english <- !in_czech
if(in_czech) {
  lang <- "CZ"
} else {
  lang <- "EN"
}


possible_questions <- c("k","avg_add","relative_add")
ix <- sample(1:length(possible_questions), 1)
coef_type <- possible_questions[ix]

```

```{r data generation, echo = FALSE}
library(lubridate)
library(tidyverse)
t_max <- sample(8:14,1)
t <- 1:t_max
end_date <- lubridate::today() 
start_date <- end_date - years(100)
used_date <- sample(as.numeric(start_date):as.numeric(end_date),1)
df <- tibble(datum = as_date(used_date),.rows = t_max)
for (i in 2:t_max) {
  df$datum[i] <- df$datum[i-1]
  month(df$datum[i]) <- month(df$datum[i-1]) + (1)
  
}
should_continue <- T

while(should_continue) {
  if(runif(1) < 0.5) {
    is_trend <- F
    m <- sample(500:8000,1)
    
    intercept <- m
    slope <- runif(1,-0.1,1)
    z <- 0 + slope*t + rnorm(t_max,0,0.1)
    
    df$y <- round(z*sdx + m,0)
  } else {
    is_trend <- T
    m <- sample(500:8000,1)
    sdx <- sample(100:500,1)
    intercept <- m
    slope <- runif(1,-0.1,1)
    z <- 0 + slope*t + rnorm(t_max,0,0.1)
    
    df$y <- round(z*sdx + m,0)
  }
  
  avg_add_mean <- (df$y[t_max]-df$y[1])/(t_max-1)
  k_mean <- (df$y[t_max]/df$y[1])^(1/(t_max-1))
  relative_mean <- k_mean - 1
  should_continue <- F
}



if(coef_type == "k") {
  coef <- k_mean
  coef_text <- "koeficient růstu"
  explanation_text <- sprintf("Průměrný koeficient růstu je %.2f.",coef)
} else if(coef_type == "avg_add") {
  coef <- avg_add_mean
  coef_text <- "absolutní přírůstek"
  explanation_text <- sprintf("Průměrný absolutní přírůstek je %.2f.",coef)
} else {
  coef <- relative_mean
  coef_text <- "relativní přírůstek"
  explanation_text <- sprintf("Průměrný relativní přírůstek je %.2f.",coef)
}

if(lang == "CZ") {
  exam_title <- "Časové řady"
} else {
  exam_title <- "Time series"
}



```



Question
========

Máte následující časovou řadu:

```{r , echo = FALSE}
knitr::kable(df)
```

Spočítejte pro tuto řadu průměrný `r coef_text`.

Solution
========

`r explanation_text`

Meta-information
================
extype: num
exsolution: `r exams::fmt(coef,2)`
exname: time_series
extitle: `r exam_title`
expoints: 1
extol: 0.01
